services:
  main-application:
    container_name: main-application
    working_dir: /servers/notebook-app/application
    build:
      context: .
      dockerfile: Dockerfile
    command: /servers/notebook-app/application/server.exe
    ports:
      - "8081:8080"
    volumes:
      - ./logs/log.log:/go/src/app/log.log
      - ./internal/config/config.yaml:/servers/notebook-app/application/config.yaml
    depends_on:
      - postgres-master
    networks:
      - noteappnetwork

  main-application-ro1:
    container_name: main-application-ro1
    working_dir: /servers/notebook-app/application
    build:
      context: .
      dockerfile: Dockerfile
    command: /servers/notebook-app/application/server.exe
    ports:
      - "8082:8080"
    volumes:
      - ./logs/log-ro1.log:/go/src/app/log.log
      - ./internal/config/config-ro.yaml:/servers/notebook-app/application/config.yaml
    depends_on:
      - postgres-slave
    networks:
      - noteappnetwork

  main-application-ro2:
    container_name: main-application-ro2
    working_dir: /servers/notebook-app/application
    build:
      context: .
      dockerfile: Dockerfile
    command: /servers/notebook-app/application/server.exe
    ports:
      - "8083:8080"
    volumes:
      - ./logs/log-ro2.log:/go/src/app/log.log
      - ./internal/config/config-ro.yaml:/servers/notebook-app/application/config.yaml
    depends_on:
      - postgres-slave
    networks:
      - noteappnetwork

  main-application-mirror:
    container_name: main-application-mirror
    working_dir: /servers/notebook-app/application
    build:
      context: .
      dockerfile: Dockerfile
    command: /servers/notebook-app/application/server.exe
    ports:
      - "8084:8080"
    volumes:
      - ./logs/log-mirror.log:/go/src/app/log.log
      - ./internal/config/config.yaml:/servers/notebook-app/application/config.yaml
    depends_on:
      - postgres-master
    networks:
      - noteappnetwork

  postgres-master:
    container_name: postgres-master
    image: bitnami/postgresql:16
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "NotebookApp"
      POSTGRESQL_REPLICATION_MODE: "master"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "password"
    ports:
      - "15432:5432"
    volumes:
      - ./initdb/create_main.sql:/docker-entrypoint-initdb.d/init.sql
      - /servers/notebook-app/docker-data/postgres-master-data:/var/lib/postgresql/data
    networks:
      - noteappnetwork

  postgres-slave:
    container_name: postgres-slave
    image: bitnami/postgresql:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d admin -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "NotebookApp"
      POSTGRESQL_REPLICATION_MODE: "slave"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "password"
      POSTGRESQL_MASTER_HOST: "postgres-master"
    depends_on:
      postgres-master:
        condition: service_healthy
    ports:
      - "15433:5432"
    volumes:
      - /servers/notebook-app/docker-data/postgres-slave-data:/var/lib/postgresql/data
    networks:
      - noteappnetwork

  pgadmin:
    image: dpage/pgadmin4:7
    ports:
      - 5435:80
    volumes:
      - /servers/notebook-app/docker-data/pgadmin-data:/var/lib/pgadmin
    environment:
      TZ: "Europe/Moscow"
      PGADMIN_DEFAULT_EMAIL: root@root.root
      PGADMIN_DEFAULT_PASSWORD: rootadmin
    depends_on:
      - postgres-master
    networks:
      - noteappnetwork

networks:
  noteappnetwork:
    driver: bridge
