services:
  cd-backend:
    container_name: cd-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/main
    ports:
      - "8081:8080"
    volumes:
      - ./log.log:/app/log.log
      - ./backend/config/config.yaml:/app/config.yaml
    depends_on:
      - postgres-master
    networks:
      - noteappnetwork

  cd-backend-ro1:
    container_name: cd-backend-ro1
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/main
    ports:
      - "8082:8080"
    volumes:
      - ./log-ro1.log:/app/log.log
      - ./backend/config/config-ro.yaml:/app/config.yaml
    depends_on:
      - postgres-slave
    networks:
      - noteappnetwork

  cd-backend-ro2:
    container_name: cd-backend-ro2
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/main
    ports:
      - "8083:8080"
    volumes:
      - ./log-ro2.log:/app/log.log
      - ./backend/config/config-ro.yaml:/app/config.yaml
    depends_on:
      - postgres-slave
    networks:
      - noteappnetwork

  cd-backend-mirror:
    container_name: cd-backend-mirror
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/main
    ports:
      - "8084:8080"
    volumes:
      - ./log-mirror.log:/app/log.log
      - ./backend/config/config.yaml:/app/config.yaml
    depends_on:
      - postgres-master
    networks:
      - noteappnetwork

  postgres-master:
    container_name: postgres-master
    image: bitnami/postgresql:16
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "NotebookApp"
      POSTGRESQL_REPLICATION_MODE: "master"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "1337"
    ports:
      - "15432:5432"
    volumes:
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    networks:
      - noteappnetwork

  postgres-slave:
    container_name: postgres-slave
    image: bitnami/postgresql:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d admin -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "NotebookApp"
      POSTGRESQL_REPLICATION_MODE: "slave"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "password"
      POSTGRESQL_MASTER_HOST: "postgres-master"
    depends_on:
      postgres-master:
        condition: service_healthy
    ports:
      - "15433:5432"
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      - noteappnetwork

  pgadmin:
    image: dpage/pgadmin4:7
    env_file:
      - .env
    ports:
      - 5435:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      - postgres-master
    networks:
      - cookdroognet

    restart: unless-stopped

networks:
  noteappnetwork:
    driver: bridge