worker_processes  1;

events {
    worker_connections  1024;
}

http {

    proxy_pass_request_headers on;
    underscores_in_headers on;

    server {
        listen 8080;
        server_name  localhost;

        add_header Access-Control-Allow-Origin *;

        location / {
            alias  /home/daemo/Документы/University/ppo-and-db/application/static;
            index index.html;
        }

        location /test {
            alias  /home/daemo/Документы/University/ppo-and-db/application/static;
            index index.html;
        }

        location = /api/v2 {
            alias  /home/daemo/Документы/University/ppo-and-db/application/docs;
            index openapi.yaml;
        }

        location /api/v2 {
            proxy_pass http://localhost:8081;
        }

        location /legacy {
            return 301 https://github.com/DionisPalpatin/ppo-and-db/tree/master/application/internal/UI/TechUI;
        }

        location /documentation {
            alias /home/daemo/Документы/University/ppo-and-db/application/docs;
            index readme.html;
        }

        location /admin {
            return 301 http://localhost:5432;
        }

        location /status {
            stub_status on;
        }
    }
}
