worker_processes  1;
user nginx;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    proxy_pass_request_headers on;
    underscores_in_headers on;

    server {
        listen 8080;
        server_name  localhost;

        add_header Access-Control-Allow-Origin *;

        location / {
            alias /servers/notebook-app/static/;
            index index.html;
        }

        location /test {
            alias /servers/notebook-app/static/;
            index index.html;
        }

        location /api/v1/docs/ {
            alias /servers/notebook-app/docs/;
            index index.html;
            try_files $uri $uri/ /api/v1/docs/index.html;
        }

        location /api/v1/ {
            proxy_pass http://localhost:8081/;
        }

        location = /api/v1 {
            return 301 /api/v1/docs/;
        }

        location /legacy {
            return 301 https://github.com/DionisPalpatin/ppo-and-db/tree/master/application/internal/UI/TechUI;
        }

        location /documentation {
            alias /servers/notebook-app/static;
            index README.html;
        }

        location /admin {
            return 301 http://localhost:5435;
        }

        location /status {
            stub_status on;
        }
    }
}