// Code generated by mockery v2.49.1. DO NOT EDIT.

package v2

import (
	bl "github.com/DionisPalpatin/ppo-and-db/application/internal/business-logic"
	mock "github.com/stretchr/testify/mock"

	models "github.com/DionisPalpatin/ppo-and-db/application/internal/models"
)

// MockCollectionRepository is an autogenerated mock type for the MockCollectionRepository type
type MockCollectionRepository struct {
	mock.Mock
}

type MockCollectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionRepository) EXPECT() *MockCollectionRepository_Expecter {
	return &MockCollectionRepository_Expecter{mock: &_m.Mock}
}

// AddCollection provides a mock function with given fields: collection
func (_m *MockCollectionRepository) AddCollection(collection *models.Collection) (int, *bl.MyError) {
	ret := _m.Called(collection)

	if len(ret) == 0 {
		panic("no return value specified for AddCollection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Collection) *bl.MyError); ok {
		r0 = rf(collection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return 0, r0
}

// MockCollectionRepository_AddCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCollection'
type MockCollectionRepository_AddCollection_Call struct {
	*mock.Call
}

// AddCollection is a helper method to define mock.On call
//   - collection *models.Collection
func (_e *MockCollectionRepository_Expecter) AddCollection(collection interface{}) *MockCollectionRepository_AddCollection_Call {
	return &MockCollectionRepository_AddCollection_Call{Call: _e.mock.On("AddCollection", collection)}
}

func (_c *MockCollectionRepository_AddCollection_Call) Run(run func(collection *models.Collection)) *MockCollectionRepository_AddCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_AddCollection_Call) Return(_a0 *bl.MyError) *MockCollectionRepository_AddCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollectionRepository_AddCollection_Call) RunAndReturn(run func(*models.Collection) *bl.MyError) *MockCollectionRepository_AddCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: id
func (_m *MockCollectionRepository) DeleteCollection(id int) *bl.MyError {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) *bl.MyError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockCollectionRepository_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockCollectionRepository_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - id int
func (_e *MockCollectionRepository_Expecter) DeleteCollection(id interface{}) *MockCollectionRepository_DeleteCollection_Call {
	return &MockCollectionRepository_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", id)}
}

func (_c *MockCollectionRepository_DeleteCollection_Call) Run(run func(id int)) *MockCollectionRepository_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCollectionRepository_DeleteCollection_Call) Return(_a0 *bl.MyError) *MockCollectionRepository_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollectionRepository_DeleteCollection_Call) RunAndReturn(run func(int) *bl.MyError) *MockCollectionRepository_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCollections provides a mock function with given fields:
func (_m *MockCollectionRepository) GetAllCollections() ([]*models.Collection, *bl.MyError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCollections")
	}

	var r0 []*models.Collection
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func() ([]*models.Collection, *bl.MyError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Collection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func() *bl.MyError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockCollectionRepository_GetAllCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCollections'
type MockCollectionRepository_GetAllCollections_Call struct {
	*mock.Call
}

// GetAllCollections is a helper method to define mock.On call
func (_e *MockCollectionRepository_Expecter) GetAllCollections() *MockCollectionRepository_GetAllCollections_Call {
	return &MockCollectionRepository_GetAllCollections_Call{Call: _e.mock.On("GetAllCollections")}
}

func (_c *MockCollectionRepository_GetAllCollections_Call) Run(run func()) *MockCollectionRepository_GetAllCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectionRepository_GetAllCollections_Call) Return(_a0 []*models.Collection, _a1 *bl.MyError) *MockCollectionRepository_GetAllCollections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_GetAllCollections_Call) RunAndReturn(run func() ([]*models.Collection, *bl.MyError)) *MockCollectionRepository_GetAllCollections_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllNotesInCollection provides a mock function with given fields: collection
func (_m *MockCollectionRepository) GetAllNotesInCollection(collection *models.Collection) ([]*models.Note, *bl.MyError) {
	ret := _m.Called(collection)

	if len(ret) == 0 {
		panic("no return value specified for GetAllNotesInCollection")
	}

	var r0 []*models.Note
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Collection) ([]*models.Note, *bl.MyError)); ok {
		return rf(collection)
	}
	if rf, ok := ret.Get(0).(func(*models.Collection) []*models.Note); ok {
		r0 = rf(collection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Collection) *bl.MyError); ok {
		r1 = rf(collection)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockCollectionRepository_GetAllNotesInCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllNotesInCollection'
type MockCollectionRepository_GetAllNotesInCollection_Call struct {
	*mock.Call
}

// GetAllNotesInCollection is a helper method to define mock.On call
//   - collection *models.Collection
func (_e *MockCollectionRepository_Expecter) GetAllNotesInCollection(collection interface{}) *MockCollectionRepository_GetAllNotesInCollection_Call {
	return &MockCollectionRepository_GetAllNotesInCollection_Call{Call: _e.mock.On("GetAllNotesInCollection", collection)}
}

func (_c *MockCollectionRepository_GetAllNotesInCollection_Call) Run(run func(collection *models.Collection)) *MockCollectionRepository_GetAllNotesInCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_GetAllNotesInCollection_Call) Return(_a0 []*models.Note, _a1 *bl.MyError) *MockCollectionRepository_GetAllNotesInCollection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_GetAllNotesInCollection_Call) RunAndReturn(run func(*models.Collection) ([]*models.Note, *bl.MyError)) *MockCollectionRepository_GetAllNotesInCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUserCollections provides a mock function with given fields: user
func (_m *MockCollectionRepository) GetAllUserCollections(user *models.User) ([]*models.Collection, *bl.MyError) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUserCollections")
	}

	var r0 []*models.Collection
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.User) ([]*models.Collection, *bl.MyError)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*models.User) []*models.Collection); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.User) *bl.MyError); ok {
		r1 = rf(user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockCollectionRepository_GetAllUserCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUserCollections'
type MockCollectionRepository_GetAllUserCollections_Call struct {
	*mock.Call
}

// GetAllUserCollections is a helper method to define mock.On call
//   - user *models.User
func (_e *MockCollectionRepository_Expecter) GetAllUserCollections(user interface{}) *MockCollectionRepository_GetAllUserCollections_Call {
	return &MockCollectionRepository_GetAllUserCollections_Call{Call: _e.mock.On("GetAllUserCollections", user)}
}

func (_c *MockCollectionRepository_GetAllUserCollections_Call) Run(run func(user *models.User)) *MockCollectionRepository_GetAllUserCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *MockCollectionRepository_GetAllUserCollections_Call) Return(_a0 []*models.Collection, _a1 *bl.MyError) *MockCollectionRepository_GetAllUserCollections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_GetAllUserCollections_Call) RunAndReturn(run func(*models.User) ([]*models.Collection, *bl.MyError)) *MockCollectionRepository_GetAllUserCollections_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollectionByID provides a mock function with given fields: id
func (_m *MockCollectionRepository) GetCollectionByID(id int) (*models.Collection, *bl.MyError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCollectionByID")
	}

	var r0 *models.Collection
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) (*models.Collection, *bl.MyError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Collection); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *bl.MyError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockCollectionRepository_GetCollectionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollectionByID'
type MockCollectionRepository_GetCollectionByID_Call struct {
	*mock.Call
}

// GetCollectionByID is a helper method to define mock.On call
//   - id int
func (_e *MockCollectionRepository_Expecter) GetCollectionByID(id interface{}) *MockCollectionRepository_GetCollectionByID_Call {
	return &MockCollectionRepository_GetCollectionByID_Call{Call: _e.mock.On("GetCollectionByID", id)}
}

func (_c *MockCollectionRepository_GetCollectionByID_Call) Run(run func(id int)) *MockCollectionRepository_GetCollectionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCollectionRepository_GetCollectionByID_Call) Return(_a0 *models.Collection, _a1 *bl.MyError) *MockCollectionRepository_GetCollectionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_GetCollectionByID_Call) RunAndReturn(run func(int) (*models.Collection, *bl.MyError)) *MockCollectionRepository_GetCollectionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollectionByName provides a mock function with given fields: name
func (_m *MockCollectionRepository) GetCollectionByName(name string) (*models.Collection, *bl.MyError) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCollectionByName")
	}

	var r0 *models.Collection
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(string) (*models.Collection, *bl.MyError)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Collection); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *bl.MyError); ok {
		r1 = rf(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockCollectionRepository_GetCollectionByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollectionByName'
type MockCollectionRepository_GetCollectionByName_Call struct {
	*mock.Call
}

// GetCollectionByName is a helper method to define mock.On call
//   - name string
func (_e *MockCollectionRepository_Expecter) GetCollectionByName(name interface{}) *MockCollectionRepository_GetCollectionByName_Call {
	return &MockCollectionRepository_GetCollectionByName_Call{Call: _e.mock.On("GetCollectionByName", name)}
}

func (_c *MockCollectionRepository_GetCollectionByName_Call) Run(run func(name string)) *MockCollectionRepository_GetCollectionByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCollectionRepository_GetCollectionByName_Call) Return(_a0 *models.Collection, _a1 *bl.MyError) *MockCollectionRepository_GetCollectionByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollectionRepository_GetCollectionByName_Call) RunAndReturn(run func(string) (*models.Collection, *bl.MyError)) *MockCollectionRepository_GetCollectionByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCollection provides a mock function with given fields: collection
func (_m *MockCollectionRepository) UpdateCollection(collection *models.Collection) *bl.MyError {
	ret := _m.Called(collection)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCollection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Collection) *bl.MyError); ok {
		r0 = rf(collection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockCollectionRepository_UpdateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCollection'
type MockCollectionRepository_UpdateCollection_Call struct {
	*mock.Call
}

// UpdateCollection is a helper method to define mock.On call
//   - collection *models.Collection
func (_e *MockCollectionRepository_Expecter) UpdateCollection(collection interface{}) *MockCollectionRepository_UpdateCollection_Call {
	return &MockCollectionRepository_UpdateCollection_Call{Call: _e.mock.On("UpdateCollection", collection)}
}

func (_c *MockCollectionRepository_UpdateCollection_Call) Run(run func(collection *models.Collection)) *MockCollectionRepository_UpdateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Collection))
	})
	return _c
}

func (_c *MockCollectionRepository_UpdateCollection_Call) Return(_a0 *bl.MyError) *MockCollectionRepository_UpdateCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollectionRepository_UpdateCollection_Call) RunAndReturn(run func(*models.Collection) *bl.MyError) *MockCollectionRepository_UpdateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCollectionRepository creates a new instance of MockCollectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionRepository {
	mock := &MockCollectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
