// Code generated by mockery v2.49.1. DO NOT EDIT.

package v2

import (
	bl "github.com/DionisPalpatin/ppo-and-db/application/internal/business_logic"
	mock "github.com/stretchr/testify/mock"

	models "github.com/DionisPalpatin/ppo-and-db/application/internal/models"
)

// MockNoteRepository is an autogenerated mock type for the MockNoteRepository type
type MockNoteRepository struct {
	mock.Mock
}

type MockNoteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoteRepository) EXPECT() *MockNoteRepository_Expecter {
	return &MockNoteRepository_Expecter{mock: &_m.Mock}
}

// AddNote provides a mock function with given fields: note
func (_m *MockNoteRepository) AddNote(note *models.Note) (int, *bl.MyError) {
	ret := _m.Called(note)

	if len(ret) == 0 {
		panic("no return value specified for AddNote")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Note) *bl.MyError); ok {
		r0 = rf(note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return 0, r0
}

// MockNoteRepository_AddNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNote'
type MockNoteRepository_AddNote_Call struct {
	*mock.Call
}

// AddNote is a helper method to define mock.On call
//   - note *models.Note
func (_e *MockNoteRepository_Expecter) AddNote(note interface{}) *MockNoteRepository_AddNote_Call {
	return &MockNoteRepository_AddNote_Call{Call: _e.mock.On("AddNote", note)}
}

func (_c *MockNoteRepository_AddNote_Call) Run(run func(note *models.Note)) *MockNoteRepository_AddNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Note))
	})
	return _c
}

func (_c *MockNoteRepository_AddNote_Call) Return(_a0 *bl.MyError) *MockNoteRepository_AddNote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoteRepository_AddNote_Call) RunAndReturn(run func(*models.Note) *bl.MyError) *MockNoteRepository_AddNote_Call {
	_c.Call.Return(run)
	return _c
}

// AddNoteToCollection provides a mock function with given fields: collectionID, noteID
func (_m *MockNoteRepository) AddNoteToCollection(collectionID int, noteID int) *bl.MyError {
	ret := _m.Called(collectionID, noteID)

	if len(ret) == 0 {
		panic("no return value specified for AddNoteToCollection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int, int) *bl.MyError); ok {
		r0 = rf(collectionID, noteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockNoteRepository_AddNoteToCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNoteToCollection'
type MockNoteRepository_AddNoteToCollection_Call struct {
	*mock.Call
}

// AddNoteToCollection is a helper method to define mock.On call
//   - collectionID int
//   - noteID int
func (_e *MockNoteRepository_Expecter) AddNoteToCollection(collectionID interface{}, noteID interface{}) *MockNoteRepository_AddNoteToCollection_Call {
	return &MockNoteRepository_AddNoteToCollection_Call{Call: _e.mock.On("AddNoteToCollection", collectionID, noteID)}
}

func (_c *MockNoteRepository_AddNoteToCollection_Call) Run(run func(collectionID int, noteID int)) *MockNoteRepository_AddNoteToCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockNoteRepository_AddNoteToCollection_Call) Return(_a0 *bl.MyError) *MockNoteRepository_AddNoteToCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoteRepository_AddNoteToCollection_Call) RunAndReturn(run func(int, int) *bl.MyError) *MockNoteRepository_AddNoteToCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNote provides a mock function with given fields: id
func (_m *MockNoteRepository) DeleteNote(id int) *bl.MyError {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNote")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) *bl.MyError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockNoteRepository_DeleteNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNote'
type MockNoteRepository_DeleteNote_Call struct {
	*mock.Call
}

// DeleteNote is a helper method to define mock.On call
//   - id int
func (_e *MockNoteRepository_Expecter) DeleteNote(id interface{}) *MockNoteRepository_DeleteNote_Call {
	return &MockNoteRepository_DeleteNote_Call{Call: _e.mock.On("DeleteNote", id)}
}

func (_c *MockNoteRepository_DeleteNote_Call) Run(run func(id int)) *MockNoteRepository_DeleteNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockNoteRepository_DeleteNote_Call) Return(_a0 *bl.MyError) *MockNoteRepository_DeleteNote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoteRepository_DeleteNote_Call) RunAndReturn(run func(int) *bl.MyError) *MockNoteRepository_DeleteNote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNoteFromCollection provides a mock function with given fields: collectionID, noteID
func (_m *MockNoteRepository) DeleteNoteFromCollection(collectionID int, noteID int) *bl.MyError {
	ret := _m.Called(collectionID, noteID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNoteFromCollection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int, int) *bl.MyError); ok {
		r0 = rf(collectionID, noteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockNoteRepository_DeleteNoteFromCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNoteFromCollection'
type MockNoteRepository_DeleteNoteFromCollection_Call struct {
	*mock.Call
}

// DeleteNoteFromCollection is a helper method to define mock.On call
//   - collectionID int
//   - noteID int
func (_e *MockNoteRepository_Expecter) DeleteNoteFromCollection(collectionID interface{}, noteID interface{}) *MockNoteRepository_DeleteNoteFromCollection_Call {
	return &MockNoteRepository_DeleteNoteFromCollection_Call{Call: _e.mock.On("DeleteNoteFromCollection", collectionID, noteID)}
}

func (_c *MockNoteRepository_DeleteNoteFromCollection_Call) Run(run func(collectionID int, noteID int)) *MockNoteRepository_DeleteNoteFromCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockNoteRepository_DeleteNoteFromCollection_Call) Return(_a0 *bl.MyError) *MockNoteRepository_DeleteNoteFromCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoteRepository_DeleteNoteFromCollection_Call) RunAndReturn(run func(int, int) *bl.MyError) *MockNoteRepository_DeleteNoteFromCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllNotes provides a mock function with given fields:
func (_m *MockNoteRepository) GetAllNotes() ([]*models.Note, *bl.MyError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllNotes")
	}

	var r0 []*models.Note
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func() ([]*models.Note, *bl.MyError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Note); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func() *bl.MyError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockNoteRepository_GetAllNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllNotes'
type MockNoteRepository_GetAllNotes_Call struct {
	*mock.Call
}

// GetAllNotes is a helper method to define mock.On call
func (_e *MockNoteRepository_Expecter) GetAllNotes() *MockNoteRepository_GetAllNotes_Call {
	return &MockNoteRepository_GetAllNotes_Call{Call: _e.mock.On("GetAllNotes")}
}

func (_c *MockNoteRepository_GetAllNotes_Call) Run(run func()) *MockNoteRepository_GetAllNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNoteRepository_GetAllNotes_Call) Return(_a0 []*models.Note, _a1 *bl.MyError) *MockNoteRepository_GetAllNotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNoteRepository_GetAllNotes_Call) RunAndReturn(run func() ([]*models.Note, *bl.MyError)) *MockNoteRepository_GetAllNotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPublicNotes provides a mock function with given fields:
func (_m *MockNoteRepository) GetAllPublicNotes() ([]*models.Note, *bl.MyError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllPublicNotes")
	}

	var r0 []*models.Note
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func() ([]*models.Note, *bl.MyError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Note); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func() *bl.MyError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockNoteRepository_GetAllPublicNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPublicNotes'
type MockNoteRepository_GetAllPublicNotes_Call struct {
	*mock.Call
}

// GetAllPublicNotes is a helper method to define mock.On call
func (_e *MockNoteRepository_Expecter) GetAllPublicNotes() *MockNoteRepository_GetAllPublicNotes_Call {
	return &MockNoteRepository_GetAllPublicNotes_Call{Call: _e.mock.On("GetAllPublicNotes")}
}

func (_c *MockNoteRepository_GetAllPublicNotes_Call) Run(run func()) *MockNoteRepository_GetAllPublicNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNoteRepository_GetAllPublicNotes_Call) Return(_a0 []*models.Note, _a1 *bl.MyError) *MockNoteRepository_GetAllPublicNotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNoteRepository_GetAllPublicNotes_Call) RunAndReturn(run func() ([]*models.Note, *bl.MyError)) *MockNoteRepository_GetAllPublicNotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetNoteByID provides a mock function with given fields: id
func (_m *MockNoteRepository) GetNoteByID(id int) (*models.Note, *bl.MyError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetNoteByID")
	}

	var r0 *models.Note
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) (*models.Note, *bl.MyError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Note); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *bl.MyError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockNoteRepository_GetNoteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoteByID'
type MockNoteRepository_GetNoteByID_Call struct {
	*mock.Call
}

// GetNoteByID is a helper method to define mock.On call
//   - id int
func (_e *MockNoteRepository_Expecter) GetNoteByID(id interface{}) *MockNoteRepository_GetNoteByID_Call {
	return &MockNoteRepository_GetNoteByID_Call{Call: _e.mock.On("GetNoteByID", id)}
}

func (_c *MockNoteRepository_GetNoteByID_Call) Run(run func(id int)) *MockNoteRepository_GetNoteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockNoteRepository_GetNoteByID_Call) Return(_a0 *models.Note, _a1 *bl.MyError) *MockNoteRepository_GetNoteByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNoteRepository_GetNoteByID_Call) RunAndReturn(run func(int) (*models.Note, *bl.MyError)) *MockNoteRepository_GetNoteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNoteByName provides a mock function with given fields: name
func (_m *MockNoteRepository) GetNoteByName(name string) (*models.Note, *bl.MyError) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetNoteByName")
	}

	var r0 *models.Note
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(string) (*models.Note, *bl.MyError)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Note); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *bl.MyError); ok {
		r1 = rf(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockNoteRepository_GetNoteByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoteByName'
type MockNoteRepository_GetNoteByName_Call struct {
	*mock.Call
}

// GetNoteByName is a helper method to define mock.On call
//   - name string
func (_e *MockNoteRepository_Expecter) GetNoteByName(name interface{}) *MockNoteRepository_GetNoteByName_Call {
	return &MockNoteRepository_GetNoteByName_Call{Call: _e.mock.On("GetNoteByName", name)}
}

func (_c *MockNoteRepository_GetNoteByName_Call) Run(run func(name string)) *MockNoteRepository_GetNoteByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNoteRepository_GetNoteByName_Call) Return(_a0 *models.Note, _a1 *bl.MyError) *MockNoteRepository_GetNoteByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNoteRepository_GetNoteByName_Call) RunAndReturn(run func(string) (*models.Note, *bl.MyError)) *MockNoteRepository_GetNoteByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNoteContent provides a mock function with given fields: note
func (_m *MockNoteRepository) UpdateNoteContent(note *models.Note) *bl.MyError {
	ret := _m.Called(note)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNoteContent")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Note) *bl.MyError); ok {
		r0 = rf(note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockNoteRepository_UpdateNoteContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNoteContent'
type MockNoteRepository_UpdateNoteContent_Call struct {
	*mock.Call
}

// UpdateNoteContent is a helper method to define mock.On call
//   - note *models.Note
func (_e *MockNoteRepository_Expecter) UpdateNoteContent(note interface{}) *MockNoteRepository_UpdateNoteContent_Call {
	return &MockNoteRepository_UpdateNoteContent_Call{Call: _e.mock.On("UpdateNoteContent", note)}
}

func (_c *MockNoteRepository_UpdateNoteContent_Call) Run(run func(note *models.Note)) *MockNoteRepository_UpdateNoteContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Note))
	})
	return _c
}

func (_c *MockNoteRepository_UpdateNoteContent_Call) Return(_a0 *bl.MyError) *MockNoteRepository_UpdateNoteContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoteRepository_UpdateNoteContent_Call) RunAndReturn(run func(*models.Note) *bl.MyError) *MockNoteRepository_UpdateNoteContent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNoteInfo provides a mock function with given fields: note
func (_m *MockNoteRepository) UpdateNoteInfo(note *models.Note) *bl.MyError {
	ret := _m.Called(note)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNoteInfo")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Note) *bl.MyError); ok {
		r0 = rf(note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockNoteRepository_UpdateNoteInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNoteInfo'
type MockNoteRepository_UpdateNoteInfo_Call struct {
	*mock.Call
}

// UpdateNoteInfo is a helper method to define mock.On call
//   - note *models.Note
func (_e *MockNoteRepository_Expecter) UpdateNoteInfo(note interface{}) *MockNoteRepository_UpdateNoteInfo_Call {
	return &MockNoteRepository_UpdateNoteInfo_Call{Call: _e.mock.On("UpdateNoteInfo", note)}
}

func (_c *MockNoteRepository_UpdateNoteInfo_Call) Run(run func(note *models.Note)) *MockNoteRepository_UpdateNoteInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Note))
	})
	return _c
}

func (_c *MockNoteRepository_UpdateNoteInfo_Call) Return(_a0 *bl.MyError) *MockNoteRepository_UpdateNoteInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoteRepository_UpdateNoteInfo_Call) RunAndReturn(run func(*models.Note) *bl.MyError) *MockNoteRepository_UpdateNoteInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNoteRepository creates a new instance of MockNoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoteRepository {
	mock := &MockNoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
