// Code generated by mockery v2.49.1. DO NOT EDIT.

package v2

import (
	bl "github.com/DionisPalpatin/ppo-and-db/application/internal/business_logic"
	mock "github.com/stretchr/testify/mock"

	models "github.com/DionisPalpatin/ppo-and-db/application/internal/models"
)

// MockSectionRepository is an autogenerated mock type for the MockSectionRepository type
type MockSectionRepository struct {
	mock.Mock
}

type MockSectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSectionRepository) EXPECT() *MockSectionRepository_Expecter {
	return &MockSectionRepository_Expecter{mock: &_m.Mock}
}

// AddNoteToSection provides a mock function with given fields: note, section
func (_m *MockSectionRepository) AddNoteToSection(note *models.Note, section *models.Section) *bl.MyError {
	ret := _m.Called(note, section)

	if len(ret) == 0 {
		panic("no return value specified for AddNoteToSection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Note, *models.Section) *bl.MyError); ok {
		r0 = rf(note, section)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockSectionRepository_AddNoteToSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNoteToSection'
type MockSectionRepository_AddNoteToSection_Call struct {
	*mock.Call
}

// AddNoteToSection is a helper method to define mock.On call
//   - note *models.Note
//   - section *models.Section
func (_e *MockSectionRepository_Expecter) AddNoteToSection(note interface{}, section interface{}) *MockSectionRepository_AddNoteToSection_Call {
	return &MockSectionRepository_AddNoteToSection_Call{Call: _e.mock.On("AddNoteToSection", note, section)}
}

func (_c *MockSectionRepository_AddNoteToSection_Call) Run(run func(note *models.Note, section *models.Section)) *MockSectionRepository_AddNoteToSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Note), args[1].(*models.Section))
	})
	return _c
}

func (_c *MockSectionRepository_AddNoteToSection_Call) Return(_a0 *bl.MyError) *MockSectionRepository_AddNoteToSection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSectionRepository_AddNoteToSection_Call) RunAndReturn(run func(*models.Note, *models.Section) *bl.MyError) *MockSectionRepository_AddNoteToSection_Call {
	_c.Call.Return(run)
	return _c
}

// AddSection provides a mock function with given fields: section, team
func (_m *MockSectionRepository) AddSection(section *models.Section, team *models.Team) (int, *bl.MyError) {
	ret := _m.Called(section, team)

	if len(ret) == 0 {
		panic("no return value specified for AddSection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Section, *models.Team) *bl.MyError); ok {
		r0 = rf(section, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return 0, r0
}

// MockSectionRepository_AddSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSection'
type MockSectionRepository_AddSection_Call struct {
	*mock.Call
}

// AddSection is a helper method to define mock.On call
//   - section *models.Section
//   - team *models.Team
func (_e *MockSectionRepository_Expecter) AddSection(section interface{}, team interface{}) *MockSectionRepository_AddSection_Call {
	return &MockSectionRepository_AddSection_Call{Call: _e.mock.On("AddSection", section, team)}
}

func (_c *MockSectionRepository_AddSection_Call) Run(run func(section *models.Section, team *models.Team)) *MockSectionRepository_AddSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Section), args[1].(*models.Team))
	})
	return _c
}

func (_c *MockSectionRepository_AddSection_Call) Return(_a0 *bl.MyError) *MockSectionRepository_AddSection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSectionRepository_AddSection_Call) RunAndReturn(run func(*models.Section, *models.Team) *bl.MyError) *MockSectionRepository_AddSection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNoteFromSection provides a mock function with given fields: note, section
func (_m *MockSectionRepository) DeleteNoteFromSection(note *models.Note, section *models.Section) *bl.MyError {
	ret := _m.Called(note, section)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNoteFromSection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Note, *models.Section) *bl.MyError); ok {
		r0 = rf(note, section)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockSectionRepository_DeleteNoteFromSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNoteFromSection'
type MockSectionRepository_DeleteNoteFromSection_Call struct {
	*mock.Call
}

// DeleteNoteFromSection is a helper method to define mock.On call
//   - note *models.Note
//   - section *models.Section
func (_e *MockSectionRepository_Expecter) DeleteNoteFromSection(note interface{}, section interface{}) *MockSectionRepository_DeleteNoteFromSection_Call {
	return &MockSectionRepository_DeleteNoteFromSection_Call{Call: _e.mock.On("DeleteNoteFromSection", note, section)}
}

func (_c *MockSectionRepository_DeleteNoteFromSection_Call) Run(run func(note *models.Note, section *models.Section)) *MockSectionRepository_DeleteNoteFromSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Note), args[1].(*models.Section))
	})
	return _c
}

func (_c *MockSectionRepository_DeleteNoteFromSection_Call) Return(_a0 *bl.MyError) *MockSectionRepository_DeleteNoteFromSection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSectionRepository_DeleteNoteFromSection_Call) RunAndReturn(run func(*models.Note, *models.Section) *bl.MyError) *MockSectionRepository_DeleteNoteFromSection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSection provides a mock function with given fields: id
func (_m *MockSectionRepository) DeleteSection(id int) *bl.MyError {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) *bl.MyError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockSectionRepository_DeleteSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSection'
type MockSectionRepository_DeleteSection_Call struct {
	*mock.Call
}

// DeleteSection is a helper method to define mock.On call
//   - id int
func (_e *MockSectionRepository_Expecter) DeleteSection(id interface{}) *MockSectionRepository_DeleteSection_Call {
	return &MockSectionRepository_DeleteSection_Call{Call: _e.mock.On("DeleteSection", id)}
}

func (_c *MockSectionRepository_DeleteSection_Call) Run(run func(id int)) *MockSectionRepository_DeleteSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockSectionRepository_DeleteSection_Call) Return(_a0 *bl.MyError) *MockSectionRepository_DeleteSection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSectionRepository_DeleteSection_Call) RunAndReturn(run func(int) *bl.MyError) *MockSectionRepository_DeleteSection_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllNotesInSection provides a mock function with given fields: section
func (_m *MockSectionRepository) GetAllNotesInSection(section *models.Section) ([]*models.Note, *bl.MyError) {
	ret := _m.Called(section)

	if len(ret) == 0 {
		panic("no return value specified for GetAllNotesInSection")
	}

	var r0 []*models.Note
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Section) ([]*models.Note, *bl.MyError)); ok {
		return rf(section)
	}
	if rf, ok := ret.Get(0).(func(*models.Section) []*models.Note); ok {
		r0 = rf(section)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Section) *bl.MyError); ok {
		r1 = rf(section)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockSectionRepository_GetAllNotesInSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllNotesInSection'
type MockSectionRepository_GetAllNotesInSection_Call struct {
	*mock.Call
}

// GetAllNotesInSection is a helper method to define mock.On call
//   - section *models.Section
func (_e *MockSectionRepository_Expecter) GetAllNotesInSection(section interface{}) *MockSectionRepository_GetAllNotesInSection_Call {
	return &MockSectionRepository_GetAllNotesInSection_Call{Call: _e.mock.On("GetAllNotesInSection", section)}
}

func (_c *MockSectionRepository_GetAllNotesInSection_Call) Run(run func(section *models.Section)) *MockSectionRepository_GetAllNotesInSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Section))
	})
	return _c
}

func (_c *MockSectionRepository_GetAllNotesInSection_Call) Return(_a0 []*models.Note, _a1 *bl.MyError) *MockSectionRepository_GetAllNotesInSection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSectionRepository_GetAllNotesInSection_Call) RunAndReturn(run func(*models.Section) ([]*models.Note, *bl.MyError)) *MockSectionRepository_GetAllNotesInSection_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSections provides a mock function with given fields:
func (_m *MockSectionRepository) GetAllSections() ([]*models.Section, *bl.MyError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllSections")
	}

	var r0 []*models.Section
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func() ([]*models.Section, *bl.MyError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Section); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Section)
		}
	}

	if rf, ok := ret.Get(1).(func() *bl.MyError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockSectionRepository_GetAllSections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSections'
type MockSectionRepository_GetAllSections_Call struct {
	*mock.Call
}

// GetAllSections is a helper method to define mock.On call
func (_e *MockSectionRepository_Expecter) GetAllSections() *MockSectionRepository_GetAllSections_Call {
	return &MockSectionRepository_GetAllSections_Call{Call: _e.mock.On("GetAllSections")}
}

func (_c *MockSectionRepository_GetAllSections_Call) Run(run func()) *MockSectionRepository_GetAllSections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSectionRepository_GetAllSections_Call) Return(_a0 []*models.Section, _a1 *bl.MyError) *MockSectionRepository_GetAllSections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSectionRepository_GetAllSections_Call) RunAndReturn(run func() ([]*models.Section, *bl.MyError)) *MockSectionRepository_GetAllSections_Call {
	_c.Call.Return(run)
	return _c
}

// GetSectionByID provides a mock function with given fields: id
func (_m *MockSectionRepository) GetSectionByID(id int) (*models.Section, *bl.MyError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSectionByID")
	}

	var r0 *models.Section
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) (*models.Section, *bl.MyError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Section); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Section)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *bl.MyError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockSectionRepository_GetSectionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSectionByID'
type MockSectionRepository_GetSectionByID_Call struct {
	*mock.Call
}

// GetSectionByID is a helper method to define mock.On call
//   - id int
func (_e *MockSectionRepository_Expecter) GetSectionByID(id interface{}) *MockSectionRepository_GetSectionByID_Call {
	return &MockSectionRepository_GetSectionByID_Call{Call: _e.mock.On("GetSectionByID", id)}
}

func (_c *MockSectionRepository_GetSectionByID_Call) Run(run func(id int)) *MockSectionRepository_GetSectionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockSectionRepository_GetSectionByID_Call) Return(_a0 *models.Section, _a1 *bl.MyError) *MockSectionRepository_GetSectionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSectionRepository_GetSectionByID_Call) RunAndReturn(run func(int) (*models.Section, *bl.MyError)) *MockSectionRepository_GetSectionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSectionByTeamName provides a mock function with given fields: teamName
func (_m *MockSectionRepository) GetSectionByTeamName(teamName string) (*models.Section, *bl.MyError) {
	ret := _m.Called(teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetSectionByTeamName")
	}

	var r0 *models.Section
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(string) (*models.Section, *bl.MyError)); ok {
		return rf(teamName)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Section); ok {
		r0 = rf(teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Section)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *bl.MyError); ok {
		r1 = rf(teamName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockSectionRepository_GetSectionByTeamName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSectionByTeamName'
type MockSectionRepository_GetSectionByTeamName_Call struct {
	*mock.Call
}

// GetSectionByTeamName is a helper method to define mock.On call
//   - teamName string
func (_e *MockSectionRepository_Expecter) GetSectionByTeamName(teamName interface{}) *MockSectionRepository_GetSectionByTeamName_Call {
	return &MockSectionRepository_GetSectionByTeamName_Call{Call: _e.mock.On("GetSectionByTeamName", teamName)}
}

func (_c *MockSectionRepository_GetSectionByTeamName_Call) Run(run func(teamName string)) *MockSectionRepository_GetSectionByTeamName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSectionRepository_GetSectionByTeamName_Call) Return(_a0 *models.Section, _a1 *bl.MyError) *MockSectionRepository_GetSectionByTeamName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSectionRepository_GetSectionByTeamName_Call) RunAndReturn(run func(string) (*models.Section, *bl.MyError)) *MockSectionRepository_GetSectionByTeamName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSection provides a mock function with given fields: section
func (_m *MockSectionRepository) UpdateSection(section *models.Section) *bl.MyError {
	ret := _m.Called(section)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSection")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Section) *bl.MyError); ok {
		r0 = rf(section)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockSectionRepository_UpdateSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSection'
type MockSectionRepository_UpdateSection_Call struct {
	*mock.Call
}

// UpdateSection is a helper method to define mock.On call
//   - section *models.Section
func (_e *MockSectionRepository_Expecter) UpdateSection(section interface{}) *MockSectionRepository_UpdateSection_Call {
	return &MockSectionRepository_UpdateSection_Call{Call: _e.mock.On("UpdateSection", section)}
}

func (_c *MockSectionRepository_UpdateSection_Call) Run(run func(section *models.Section)) *MockSectionRepository_UpdateSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Section))
	})
	return _c
}

func (_c *MockSectionRepository_UpdateSection_Call) Return(_a0 *bl.MyError) *MockSectionRepository_UpdateSection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSectionRepository_UpdateSection_Call) RunAndReturn(run func(*models.Section) *bl.MyError) *MockSectionRepository_UpdateSection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSectionRepository creates a new instance of MockSectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSectionRepository {
	mock := &MockSectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
