// Code generated by mockery v2.49.1. DO NOT EDIT.

package v2

import (
	bl "github.com/DionisPalpatin/ppo-and-db/application/internal/business_logic"
	mock "github.com/stretchr/testify/mock"

	models "github.com/DionisPalpatin/ppo-and-db/application/internal/models"
)

// MockTeamRepository is an autogenerated mock type for the MockTeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// AddTeam provides a mock function with given fields: team
func (_m *MockTeamRepository) AddTeam(team *models.Team) (int, *bl.MyError) {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for AddTeam")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Team) *bl.MyError); ok {
		r0 = rf(team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return 0, r0
}

// MockTeamRepository_AddTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeam'
type MockTeamRepository_AddTeam_Call struct {
	*mock.Call
}

// AddTeam is a helper method to define mock.On call
//   - team *models.Team
func (_e *MockTeamRepository_Expecter) AddTeam(team interface{}) *MockTeamRepository_AddTeam_Call {
	return &MockTeamRepository_AddTeam_Call{Call: _e.mock.On("AddTeam", team)}
}

func (_c *MockTeamRepository_AddTeam_Call) Run(run func(team *models.Team)) *MockTeamRepository_AddTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Team))
	})
	return _c
}

func (_c *MockTeamRepository_AddTeam_Call) Return(_a0 *bl.MyError) *MockTeamRepository_AddTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_AddTeam_Call) RunAndReturn(run func(*models.Team) *bl.MyError) *MockTeamRepository_AddTeam_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserToTeam provides a mock function with given fields: userID, teamID
func (_m *MockTeamRepository) AddUserToTeam(userID int, teamID int) *bl.MyError {
	ret := _m.Called(userID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToTeam")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int, int) *bl.MyError); ok {
		r0 = rf(userID, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockTeamRepository_AddUserToTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToTeam'
type MockTeamRepository_AddUserToTeam_Call struct {
	*mock.Call
}

// AddUserToTeam is a helper method to define mock.On call
//   - userID int
//   - teamID int
func (_e *MockTeamRepository_Expecter) AddUserToTeam(userID interface{}, teamID interface{}) *MockTeamRepository_AddUserToTeam_Call {
	return &MockTeamRepository_AddUserToTeam_Call{Call: _e.mock.On("AddUserToTeam", userID, teamID)}
}

func (_c *MockTeamRepository_AddUserToTeam_Call) Run(run func(userID int, teamID int)) *MockTeamRepository_AddUserToTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockTeamRepository_AddUserToTeam_Call) Return(_a0 *bl.MyError) *MockTeamRepository_AddUserToTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_AddUserToTeam_Call) RunAndReturn(run func(int, int) *bl.MyError) *MockTeamRepository_AddUserToTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeam provides a mock function with given fields: id
func (_m *MockTeamRepository) DeleteTeam(id int) *bl.MyError {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) *bl.MyError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockTeamRepository_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type MockTeamRepository_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - id int
func (_e *MockTeamRepository_Expecter) DeleteTeam(id interface{}) *MockTeamRepository_DeleteTeam_Call {
	return &MockTeamRepository_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", id)}
}

func (_c *MockTeamRepository_DeleteTeam_Call) Run(run func(id int)) *MockTeamRepository_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTeamRepository_DeleteTeam_Call) Return(_a0 *bl.MyError) *MockTeamRepository_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_DeleteTeam_Call) RunAndReturn(run func(int) *bl.MyError) *MockTeamRepository_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserFromTeam provides a mock function with given fields: uid, tid
func (_m *MockTeamRepository) DeleteUserFromTeam(uid int, tid int) *bl.MyError {
	ret := _m.Called(uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserFromTeam")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int, int) *bl.MyError); ok {
		r0 = rf(uid, tid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockTeamRepository_DeleteUserFromTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserFromTeam'
type MockTeamRepository_DeleteUserFromTeam_Call struct {
	*mock.Call
}

// DeleteUserFromTeam is a helper method to define mock.On call
//   - uid int
//   - tid int
func (_e *MockTeamRepository_Expecter) DeleteUserFromTeam(uid interface{}, tid interface{}) *MockTeamRepository_DeleteUserFromTeam_Call {
	return &MockTeamRepository_DeleteUserFromTeam_Call{Call: _e.mock.On("DeleteUserFromTeam", uid, tid)}
}

func (_c *MockTeamRepository_DeleteUserFromTeam_Call) Run(run func(uid int, tid int)) *MockTeamRepository_DeleteUserFromTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockTeamRepository_DeleteUserFromTeam_Call) Return(_a0 *bl.MyError) *MockTeamRepository_DeleteUserFromTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_DeleteUserFromTeam_Call) RunAndReturn(run func(int, int) *bl.MyError) *MockTeamRepository_DeleteUserFromTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTeams provides a mock function with given fields:
func (_m *MockTeamRepository) GetAllTeams() ([]*models.Team, *bl.MyError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTeams")
	}

	var r0 []*models.Team
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func() ([]*models.Team, *bl.MyError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Team); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func() *bl.MyError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockTeamRepository_GetAllTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTeams'
type MockTeamRepository_GetAllTeams_Call struct {
	*mock.Call
}

// GetAllTeams is a helper method to define mock.On call
func (_e *MockTeamRepository_Expecter) GetAllTeams() *MockTeamRepository_GetAllTeams_Call {
	return &MockTeamRepository_GetAllTeams_Call{Call: _e.mock.On("GetAllTeams")}
}

func (_c *MockTeamRepository_GetAllTeams_Call) Run(run func()) *MockTeamRepository_GetAllTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTeamRepository_GetAllTeams_Call) Return(_a0 []*models.Team, _a1 *bl.MyError) *MockTeamRepository_GetAllTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetAllTeams_Call) RunAndReturn(run func() ([]*models.Team, *bl.MyError)) *MockTeamRepository_GetAllTeams_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByID provides a mock function with given fields: id
func (_m *MockTeamRepository) GetTeamByID(id int) (*models.Team, *bl.MyError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByID")
	}

	var r0 *models.Team
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) (*models.Team, *bl.MyError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Team); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *bl.MyError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockTeamRepository_GetTeamByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByID'
type MockTeamRepository_GetTeamByID_Call struct {
	*mock.Call
}

// GetTeamByID is a helper method to define mock.On call
//   - id int
func (_e *MockTeamRepository_Expecter) GetTeamByID(id interface{}) *MockTeamRepository_GetTeamByID_Call {
	return &MockTeamRepository_GetTeamByID_Call{Call: _e.mock.On("GetTeamByID", id)}
}

func (_c *MockTeamRepository_GetTeamByID_Call) Run(run func(id int)) *MockTeamRepository_GetTeamByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamByID_Call) Return(_a0 *models.Team, _a1 *bl.MyError) *MockTeamRepository_GetTeamByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetTeamByID_Call) RunAndReturn(run func(int) (*models.Team, *bl.MyError)) *MockTeamRepository_GetTeamByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByName provides a mock function with given fields: name
func (_m *MockTeamRepository) GetTeamByName(name string) (*models.Team, *bl.MyError) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByName")
	}

	var r0 *models.Team
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(string) (*models.Team, *bl.MyError)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Team); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *bl.MyError); ok {
		r1 = rf(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockTeamRepository_GetTeamByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByName'
type MockTeamRepository_GetTeamByName_Call struct {
	*mock.Call
}

// GetTeamByName is a helper method to define mock.On call
//   - name string
func (_e *MockTeamRepository_Expecter) GetTeamByName(name interface{}) *MockTeamRepository_GetTeamByName_Call {
	return &MockTeamRepository_GetTeamByName_Call{Call: _e.mock.On("GetTeamByName", name)}
}

func (_c *MockTeamRepository_GetTeamByName_Call) Run(run func(name string)) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamByName_Call) Return(_a0 *models.Team, _a1 *bl.MyError) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetTeamByName_Call) RunAndReturn(run func(string) (*models.Team, *bl.MyError)) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamBySectionID provides a mock function with given fields: id
func (_m *MockTeamRepository) GetTeamBySectionID(id int) (*models.Team, *bl.MyError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamBySectionID")
	}

	var r0 *models.Team
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) (*models.Team, *bl.MyError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Team); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *bl.MyError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockTeamRepository_GetTeamBySectionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamBySectionID'
type MockTeamRepository_GetTeamBySectionID_Call struct {
	*mock.Call
}

// GetTeamBySectionID is a helper method to define mock.On call
//   - id int
func (_e *MockTeamRepository_Expecter) GetTeamBySectionID(id interface{}) *MockTeamRepository_GetTeamBySectionID_Call {
	return &MockTeamRepository_GetTeamBySectionID_Call{Call: _e.mock.On("GetTeamBySectionID", id)}
}

func (_c *MockTeamRepository_GetTeamBySectionID_Call) Run(run func(id int)) *MockTeamRepository_GetTeamBySectionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamBySectionID_Call) Return(_a0 *models.Team, _a1 *bl.MyError) *MockTeamRepository_GetTeamBySectionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetTeamBySectionID_Call) RunAndReturn(run func(int) (*models.Team, *bl.MyError)) *MockTeamRepository_GetTeamBySectionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamMembers provides a mock function with given fields: teamID
func (_m *MockTeamRepository) GetTeamMembers(teamID int) ([]*models.User, *bl.MyError) {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMembers")
	}

	var r0 []*models.User
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) ([]*models.User, *bl.MyError)); ok {
		return rf(teamID)
	}
	if rf, ok := ret.Get(0).(func(int) []*models.User); ok {
		r0 = rf(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *bl.MyError); ok {
		r1 = rf(teamID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockTeamRepository_GetTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMembers'
type MockTeamRepository_GetTeamMembers_Call struct {
	*mock.Call
}

// GetTeamMembers is a helper method to define mock.On call
//   - teamID int
func (_e *MockTeamRepository_Expecter) GetTeamMembers(teamID interface{}) *MockTeamRepository_GetTeamMembers_Call {
	return &MockTeamRepository_GetTeamMembers_Call{Call: _e.mock.On("GetTeamMembers", teamID)}
}

func (_c *MockTeamRepository_GetTeamMembers_Call) Run(run func(teamID int)) *MockTeamRepository_GetTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamMembers_Call) Return(_a0 []*models.User, _a1 *bl.MyError) *MockTeamRepository_GetTeamMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetTeamMembers_Call) RunAndReturn(run func(int) ([]*models.User, *bl.MyError)) *MockTeamRepository_GetTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTeam provides a mock function with given fields: user
func (_m *MockTeamRepository) GetUserTeam(user *models.User) (*models.Team, *bl.MyError) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTeam")
	}

	var r0 *models.Team
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.User) (*models.Team, *bl.MyError)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*models.User) *models.Team); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.User) *bl.MyError); ok {
		r1 = rf(user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockTeamRepository_GetUserTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTeam'
type MockTeamRepository_GetUserTeam_Call struct {
	*mock.Call
}

// GetUserTeam is a helper method to define mock.On call
//   - user *models.User
func (_e *MockTeamRepository_Expecter) GetUserTeam(user interface{}) *MockTeamRepository_GetUserTeam_Call {
	return &MockTeamRepository_GetUserTeam_Call{Call: _e.mock.On("GetUserTeam", user)}
}

func (_c *MockTeamRepository_GetUserTeam_Call) Run(run func(user *models.User)) *MockTeamRepository_GetUserTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *MockTeamRepository_GetUserTeam_Call) Return(_a0 *models.Team, _a1 *bl.MyError) *MockTeamRepository_GetUserTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetUserTeam_Call) RunAndReturn(run func(*models.User) (*models.Team, *bl.MyError)) *MockTeamRepository_GetUserTeam_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTeam provides a mock function with given fields: team
func (_m *MockTeamRepository) UpdateTeam(team *models.Team) *bl.MyError {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeam")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.Team) *bl.MyError); ok {
		r0 = rf(team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockTeamRepository_UpdateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTeam'
type MockTeamRepository_UpdateTeam_Call struct {
	*mock.Call
}

// UpdateTeam is a helper method to define mock.On call
//   - team *models.Team
func (_e *MockTeamRepository_Expecter) UpdateTeam(team interface{}) *MockTeamRepository_UpdateTeam_Call {
	return &MockTeamRepository_UpdateTeam_Call{Call: _e.mock.On("UpdateTeam", team)}
}

func (_c *MockTeamRepository_UpdateTeam_Call) Run(run func(team *models.Team)) *MockTeamRepository_UpdateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Team))
	})
	return _c
}

func (_c *MockTeamRepository_UpdateTeam_Call) Return(_a0 *bl.MyError) *MockTeamRepository_UpdateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_UpdateTeam_Call) RunAndReturn(run func(*models.Team) *bl.MyError) *MockTeamRepository_UpdateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
