// Code generated by mockery v2.49.1. DO NOT EDIT.

package v2

import (
	bl "github.com/DionisPalpatin/ppo-and-db/application/internal/business_logic"
	mock "github.com/stretchr/testify/mock"

	models "github.com/DionisPalpatin/ppo-and-db/application/internal/models"
)

// MockUserRepository is an autogenerated mock type for the MockUserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function with given fields: user
func (_m *MockUserRepository) AddUser(user *models.User) *bl.MyError {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.User) *bl.MyError); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockUserRepository_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockUserRepository_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - user *models.User
func (_e *MockUserRepository_Expecter) AddUser(user interface{}) *MockUserRepository_AddUser_Call {
	return &MockUserRepository_AddUser_Call{Call: _e.mock.On("AddUser", user)}
}

func (_c *MockUserRepository_AddUser_Call) Run(run func(user *models.User)) *MockUserRepository_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *MockUserRepository_AddUser_Call) Return(_a0 *bl.MyError) *MockUserRepository_AddUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_AddUser_Call) RunAndReturn(run func(*models.User) *bl.MyError) *MockUserRepository_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: id
func (_m *MockUserRepository) DeleteUser(id int) *bl.MyError {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) *bl.MyError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockUserRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - id int
func (_e *MockUserRepository_Expecter) DeleteUser(id interface{}) *MockUserRepository_DeleteUser_Call {
	return &MockUserRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", id)}
}

func (_c *MockUserRepository_DeleteUser_Call) Run(run func(id int)) *MockUserRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockUserRepository_DeleteUser_Call) Return(_a0 *bl.MyError) *MockUserRepository_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_DeleteUser_Call) RunAndReturn(run func(int) *bl.MyError) *MockUserRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields:
func (_m *MockUserRepository) GetAllUsers() ([]*models.User, *bl.MyError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*models.User
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func() ([]*models.User, *bl.MyError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func() *bl.MyError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockUserRepository_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserRepository_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
func (_e *MockUserRepository_Expecter) GetAllUsers() *MockUserRepository_GetAllUsers_Call {
	return &MockUserRepository_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers")}
}

func (_c *MockUserRepository_GetAllUsers_Call) Run(run func()) *MockUserRepository_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepository_GetAllUsers_Call) Return(_a0 []*models.User, _a1 *bl.MyError) *MockUserRepository_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetAllUsers_Call) RunAndReturn(run func() ([]*models.User, *bl.MyError)) *MockUserRepository_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: id
func (_m *MockUserRepository) GetUserByID(id int) (*models.User, *bl.MyError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(int) (*models.User, *bl.MyError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *bl.MyError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - id int
func (_e *MockUserRepository_Expecter) GetUserByID(id interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", id)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(id int)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(_a0 *models.User, _a1 *bl.MyError) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(int) (*models.User, *bl.MyError)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function with given fields: login
func (_m *MockUserRepository) GetUserByLogin(login string) (*models.User, *bl.MyError) {
	ret := _m.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *models.User
	var r1 *bl.MyError
	if rf, ok := ret.Get(0).(func(string) (*models.User, *bl.MyError)); ok {
		return rf(login)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *bl.MyError); ok {
		r1 = rf(login)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bl.MyError)
		}
	}

	return r0, r1
}

// MockUserRepository_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockUserRepository_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - login string
func (_e *MockUserRepository_Expecter) GetUserByLogin(login interface{}) *MockUserRepository_GetUserByLogin_Call {
	return &MockUserRepository_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", login)}
}

func (_c *MockUserRepository_GetUserByLogin_Call) Run(run func(login string)) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByLogin_Call) Return(_a0 *models.User, _a1 *bl.MyError) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByLogin_Call) RunAndReturn(run func(string) (*models.User, *bl.MyError)) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: user
func (_m *MockUserRepository) UpdateUser(user *models.User) *bl.MyError {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *bl.MyError
	if rf, ok := ret.Get(0).(func(*models.User) *bl.MyError); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bl.MyError)
		}
	}

	return r0
}

// MockUserRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - user *models.User
func (_e *MockUserRepository_Expecter) UpdateUser(user interface{}) *MockUserRepository_UpdateUser_Call {
	return &MockUserRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", user)}
}

func (_c *MockUserRepository_UpdateUser_Call) Run(run func(user *models.User)) *MockUserRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) Return(_a0 *bl.MyError) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) RunAndReturn(run func(*models.User) *bl.MyError) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
