# PostgreSQL settings
postgres:
    psql_host:     localhost
    psql_port:     5432
    psql_user:     postgres
    psql_password: postgrespassword
    psql_db_name:   NotebookApp
    psql_schema_name: test
    db_driver_name: postgres

# Logger settings
logger:
    log_level: "debug"
#    log_file: "./log/main.log"  # for docker
    log_file: "main.log"

text_types:
    - txt
    - md
image_types:
    - jpg
    - png

system: 1
server_port: 8080

# Which UI program will use
ui_mode: "gui"

# "2006-01-02 15:04:05 -0700" -- для timestamp with tz
datetime_format: "2006-01-02 15:04:05 -0700"