name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      UNIT_SUCCESS: "0"
      INTEGRATION_SUCCESS: "0"

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io containerd.io docker-compose-plugin
      #     sudo systemctl start docker
      #     sudo systemctl enable docker
      #     sudo usermod -aG docker $USER
      #     newgrp docker

      # Start services with docker compose
      - name: Start services
        run: docker compose -f docker-compose-integration-tests.yaml up -d --build

      # Unit Tests
      - name: Run Unit Tests
        run: |
          docker compose exec tests bash -c "cd application && make unit-test && export UNIT_SUCCESS=$?"
        env:
          UNIT_SUCCESS: "0"

      # Integration Tests
      - name: Run Integration Tests
        if: env.UNIT_SUCCESS == '1'
        run: |
          docker compose exec tests bash -c "cd application && make integration-test && export INTEGRATION_SUCCESS=$?"
        env:
          UNIT_SUCCESS: ${{ env.UNIT_SUCCESS }}
          INTEGRATION_SUCCESS: "0"

      # E2E Tests
      - name: Run E2E Tests
        if: env.INTEGRATION_SUCCESS == '1'
        run: docker compose exec tests bash -c "cd application && make e2e-test"
        env:
          INTEGRATION_SUCCESS: ${{ env.INTEGRATION_SUCCESS }}

      # Generate Allure Report
      - name: Generate Allure Report
        run: docker compose exec tests bash -c "cd application && make allure"

      # Upload Allure Report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-reports
          path: allure-reports

      # Show Report (Optional, for debugging purposes)
      - name: Show Allure Report (Optional)
        if: always()
        run: docker compose exec tests bash -c "cd application && make show-report"

      # Stop services
      - name: Stop services
        if: always()
        run: docker compose down
